import type { Metadata } from "next";
import { Kanit } from "next/font/google"
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Luxono",
  description: "Generated by create next app",
};

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  preload: true,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={kanit.className}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
